### ISSUE TITLE
bug: ts-loader@4 in project breaks cypress run

### ISSUE THREAD

**Issue by valorkin** [bahmutov/add-typescript-to-cypress#23]
- version 2.0.0
- platform linux mint 18.3
- expected behavior - work :)
- actual behavior - doesn't work :)

tests build exception is `Module build failed: TypeError: Cannot read property 'afterCompile' of undefined`

works fine with ts-loader@3 but with ts-loader@4,
you will get an exception above

Regards, Dima

**Comment by stonecold123** [comment]
Yes, I'm getting the same error. Have to go back to 3.5

**Comment by Nxt3** [comment]
See this: https://github.com/bahmutov/add-typescript-to-cypress/issues/27#issuecomment-460692700

**Comment by bahmutov** [comment]
I have upgraded `ts-loader` to v5.4.5 - hope it resolves the issues
