### ISSUE TITLE
Can we uninstall this after the initial run?

### ISSUE THREAD

**Issue by Nxt3** [bahmutov/add-typescript-to-cypress#27]
After you've got everything situated--can't we remove this dependency? Maybe I'm missing something but it doesn't look like anything outside of the init is dependent on this package.

**Comment by bahmutov** [comment]
I think yes, it is not needed

**Comment by Nxt3** [comment]
Great, thank you!

**Comment by Nxt3** [comment]
@bahmutov This is incorrect then. Once we removed the package, our tests started failing.

**Comment by bahmutov** [comment]
Well you could look at the source, maybe it is required somewhere, and not just sets things up

**Comment by Nxt3** [comment]
Aren't you the author? Shouldn't you know this already?

**Comment by bahmutov** [comment]
yes I am the author. I also have written this a long time ago, and assumed you as as user did some looking at the code in order to I guess save a dependency.

**Comment by Nxt3** [comment]
For those of you that find this, you can remove this dependency after an initial run. All you have to do is install the following dependencies manually:

`@cypress/webpack-preprocessor` and `ts-loader`.

This will allow you to use the latest versions of `ts-loader` also.

**Comment by eppsilon** [comment]
FYI, `ts-loader@^6.0.0` does *not* work. Install 5.x if you're using `@cypress/webpack-preprocessor` and `ts-loader` directly.
