### ISSUE TITLE
Not compatible with newer ts-loader

### ISSUE THREAD

**Issue by scottschafer** [bahmutov/add-typescript-to-cypress#29]
Thank you for taking time to open a new issue. Please answer a few questions to help us fix it faster. You can delete text that is irrelevant to the issue.

## Is this a bug report or a feature request?

If this is a bug report, please provide as much info as possible

- version: "1.0.0"

Steps:
• Clone repo, npm install, npm run test. All works!
• Run `npm install --save-dev ts-loader`, then `npm run test` again. Dies with `Module build failed: Error: You may be using an old version of webpack; please check you're using at least version 4`

If this is a new feature request, please describe it below

**Comment by Nxt3** [comment]
See this: https://github.com/bahmutov/add-typescript-to-cypress/issues/27#issuecomment-460692700

**Comment by bahmutov** [comment]
Updated to use almost latest version of `ts-loader@5.4.5`
