### ISSUE TITLE
Don't overwrite a modified plugin file

### ISSUE THREAD

**Issue by nrutman** [bahmutov/add-typescript-to-cypress#4]
@bahmutov, how could we update this so that it doesn't overwrite the customized plugin file in my repo? Or once I've included this module's code in `plugin.js` should I remove it from the dependencies?

I'm trying to use it in a team environment, and whenever a team member clones the repo and does `npm install` they have to reset the changes to `plugin.js`.

Any thoughts?

**Comment by bahmutov** [comment]
Makes sense - it should only write itself to overwrite original plugins file, not if you have modified it

**Comment by bahmutov** [comment]
Version `2.0.0` has been published to NPM. The full release note can be found at [add-typescript-to-cypress/releases/tag/v2.0.0](https://github.com/bahmutov/add-typescript-to-cypress/releases/tag/v2.0.0).

**Tip:** safely upgrade dependency @bahmutov/add-typescript-to-cypress in your project using [next-update](https://github.com/bahmutov/next-update)

**Comment by nrutman** [comment]
Hmm...it still completely rewrote my `plugins/index.js` file...

**Comment by bahmutov** [comment]
Unfortunately the way it does this will overwrite it the first time.
