### ISSUE TITLE
No types support after package installation

### ISSUE THREAD

**Issue by Gennadiii** [bahmutov/add-typescript-to-cypress#6]
I installed the package but tsc command returns errors:
error TS2304: Cannot find name 'cy'

- cypress version: 1.4.2
- typescript version: 2.7.1
- platform: Windows 10

**Comment by bahmutov** [comment]
It is hard for me to debug a problem like this, but this works: add to the top of your spec file, see https://twitter.com/bahmutov/status/958772380834369536

**Comment by Gennadiii** [comment]
Thanks, it helped. Previously I did
const cy = require('cypress');
in a separate file ones. Then all the other files had typings. Your solution works better. It checks input parameters more precisely.
But still looks like a hack since I have to import it in code and just in one file.
