### ISSUE TITLE
npm install issue

### ISSUE THREAD

**Issue by Gennadiii** [bahmutov/add-typescript-to-cypress#9]
Is there a way to skip opening cypress once before installing the types?
What I need to do is:
npm install
tsc
npm test
And it should be in CI pipeline but npm install fails because 
> Please scaffold Cypress folder by opening Cypress once and then installing this package again
Do you have a solution for that?

Thanks!

**Comment by bahmutov** [comment]
Not yet, here is open Cypress issue for this https://github.com/cypress-io/cypress/issues/619

**Comment by Gennadiii** [comment]
Cool, thanks. Closing my issue then.
